{{- if and .Values.apiserver.enabled .Values.apiserver.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "arc.apiserver.serviceAccountName" . }}
  namespace: {{ include "arc.namespace" . }}
  labels:
    {{- include "arc.apiserver.labels" . | nindent 4 }}
  {{- with .Values.apiserver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
