{{- if and .Values.controller.enabled .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "arc.controller.fullname" . }}
  labels:
    {{- include "arc.controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "arc.controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "arc.controller.serviceAccountName" . }}
    namespace: {{ include "arc.namespace" . }}
{{- end }}
