{{- if and .Values.controller.enabled .Values.controller.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "arc.controller.serviceAccountName" . }}
  namespace: {{ include "arc.namespace" . }}
  labels:
    {{- include "arc.controller.labels" . | nindent 4 }}
  {{- with .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
